import type { Metadata } from "next";
import { COMPANY } from "@/config/company";
import { SITE } from "@/config/site";
import { LOCALE_META, LOCALES, type Locale } from "@/i18n/locales";
import { COMPANY_DISPLAY_NAME, DEFAULT_OG_IMAGE_ALT, OG_IMAGE_SIZE } from "./constants";
import { ogImageUrl } from "./og-image";
import {
  absoluteUrl,
  alternatesFor,
  alternatesForPaths,
  isHomePath,
  localizedUrl,
  type PathsByLocale,
} from "./urls";

export interface SeoImage {
  /** Absolute, or a site-relative path such as "/media/<id>". */
  url: string;
  alt: string;
  width?: number;
  height?: number;
}

export interface BuildMetadataInput {
  locale: Locale;
  /** Pathname without the locale prefix: "/", "/about", "/products/consumer-goods". */
  path: string;
  /** Page title without the site suffix (it is added here). */
  title: string;
  description: string;
  /** Defaults to the branded card generated by opengraph-image.tsx. */
  image?: SeoImage;
  type?: "website" | "article";
  noIndex?: boolean;
  publishedTime?: string | Date;
  modifiedTime?: string | Date;
  /**
   * Set when the page exists only in some locales or under a different pathname per locale (news
   * is authored per language). Without it every locale is assumed to serve `path`.
   */
  alternatePaths?: PathsByLocale;
}

const collapseWhitespace = (value: string) => value.replace(/\s+/g, " ").trim();
const mentions = (text: string, name: string) => text.toLowerCase().includes(name.toLowerCase());
const isoString = (value: string | Date) => (value instanceof Date ? value.toISOString() : value);

/**
 * "About | Shaheen Sky". The homepage is identified by the full company name instead: the name is
 * prepended unless the supplied title already carries it (Chinese title: the Chinese legal name).
 */
export function formatTitle(title: string, path: string, locale: Locale): string {
  const clean = collapseWhitespace(title);

  if (isHomePath(path)) {
    if (mentions(clean, COMPANY_DISPLAY_NAME) || mentions(clean, COMPANY.legalNameZh)) return clean;
    const name = locale === "zh" ? COMPANY.legalNameZh : COMPANY_DISPLAY_NAME;
    return clean ? `${name} | ${clean}` : name;
  }

  return mentions(clean, SITE.name) ? clean : `${clean} | ${SITE.name}`;
}

/**
 * Canonical (locale-prefixed, absolute), hreflang alternates incl. x-default, Open Graph and Twitter
 * metadata for one page. Call it from every page's generateMetadata.
 *
 * `robots` is only emitted for `noIndex`: leaving it out lets the layout's noindex (no domain
 * configured yet) apply, and a page can never re-enable indexing by accident.
 */
export function buildMetadata({
  locale,
  path,
  title,
  description,
  image,
  type = "website",
  noIndex = false,
  publishedTime,
  modifiedTime,
  alternatePaths,
}: BuildMetadataInput): Metadata {
  const fullTitle = formatTitle(title, path, locale);
  const summary = collapseWhitespace(description);
  const url = localizedUrl(locale, path);

  const languages = alternatePaths ? alternatesForPaths(alternatePaths) : alternatesFor(path);
  const alternateLocales = LOCALES.filter(
    (other) => other !== locale && (alternatePaths ? alternatePaths[other] !== undefined : true),
  ).map((other) => LOCALE_META[other].ogLocale);

  const card = image
    ? {
        url: /^https?:\/\//i.test(image.url) ? image.url : absoluteUrl(image.url),
        alt: image.alt,
        ...(image.width && image.height ? { width: image.width, height: image.height } : {}),
      }
    : { url: ogImageUrl(locale), alt: DEFAULT_OG_IMAGE_ALT, ...OG_IMAGE_SIZE };

  const openGraph = {
    title: fullTitle,
    description: summary,
    url,
    siteName: SITE.name,
    locale: LOCALE_META[locale].ogLocale,
    alternateLocale: alternateLocales,
    images: [card],
  };

  return {
    title: { absolute: fullTitle },
    description: summary,
    alternates: { canonical: url, languages },
    openGraph:
      type === "article"
        ? {
            ...openGraph,
            type: "article",
            ...(publishedTime ? { publishedTime: isoString(publishedTime) } : {}),
            ...(modifiedTime ? { modifiedTime: isoString(modifiedTime) } : {}),
          }
        : { ...openGraph, type: "website" },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description: summary,
      images: [{ url: card.url, alt: card.alt }],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}
